### ISSUE TITLE
New relase

### ISSUE THREAD

**Issue by ghost** [snitko/straight#16]
Would you be able to create a release version of the gem?

**Comment by snitko** [comment]
Just released v 0.2 of both `straight` and `straight-server`
Please check the changes. A mandatory config file section `blockchain_adapters` was introduced: https://github.com/snitko/straight-server/blob/master/templates/config.yml#L58-61

**Comment by snitko** [comment]
Actually, had to push a minor update, so `straight` is now `0.2.1`

**Comment by ghost** [comment]
@snitko Got it. Thanks! :)
